apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: ticketing
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-328203
  artifacts:
  - image: us.gcr.io/ticketing-dev-328203/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: . 
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
